# .github/workflows/cd_render.yml

name: CD on Render

on:
    workflow_run:
        workflows: ["Python application"]
        types:
          - completed

jobs:
    check_commit:
        runs-on: ubuntu-latest
        # if: ${{ contains(github.event.head_commit.message, 'DEPLOY') && github.event.workflow_run.conclusion == 'success' }}
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - uses: actions/checkout@v3
            - name: Deploy
              # Only run this step if the branch is main
              if: github.ref == 'refs/heads/main'
              env:
                  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                echo "Action has been triggered"
                echo ${{ github.event.head_commit.message }}
                echo ${{ github.event.workflow_run.conclusion == 'success' }}
              # run: |
              #    curl "$deploy_url"
